### ISSUE TITLE
Websocket requires bearer token, but websocket clients cannot provide it

### ISSUE THREAD

**Issue by tankh99** [DYOC-Chatbot/chatbot-backend#16]
Due to the limitation of websocket clients, tokens can only be placed inside the query parameters, or via cookies. We currently use tokens inside cookies, but we don't actually enable cookie authentication. Ideally, we should enable cookie authentication so that the web socket connection can be authenticated as long as the user has the correct token inside their cookies

What this essentially means is that I believe we are unable to listen to telegram messages via websocket server unless we change the current authentication method for the backend

**Comment by seelengxd** [comment]
got it - will add in my next pr
but if you need the (backend) fix urgently its adding this line to `echojwt.Config`
`TokenLookup: "header:Authorization:Bearer ,cookie:token",`
