### ISSUE TITLE
dashboard: chat component

### ISSUE THREAD

**Issue by seelengxd** [DYOC-Chatbot/chatbot-backend#18]
![Image](https://github.com/DYOC-Chatbot/chatbot-backend/assets/34371483/1333316e-52f3-46d5-a4fc-dfc41928bf44)

- [ ] backend: set up a web socket connection to listen for updates in a specific chat

**Comment by wxiaoyun** [comment]
> * backend: set up a web socket connection to listen for updates in a specific chat

If there is only going to be one / a few dashboards connected to the backend websocket, then you can just listen to the broadcast websocket endpoint - `/api/ws`. This is already implemented.

If you want to listen to specific chat, then you have to implement that
