### ISSUE TITLE
bug: unknown directive toolchain

### ISSUE THREAD

**Issue by tankh99** [DYOC-Chatbot/chatbot-backend#22]
VSCode is throwing this error for me, making the Go language server not compile as intended. Removing the toolchain line `toolchain go1.22.3` in `go.mod` works. What is the purpose of the toolchain line and can we remove it?

<img width="547" alt="Screenshot 2024-06-04 at 9 54 46 AM" src="https://github.com/DYOC-Chatbot/chatbot-backend/assets/56617918/f1b08b86-a392-4049-9633-40cb999e3f84">

**Comment by wxiaoyun** [comment]
Is it possible that your Go version is outdated?

**Comment by tankh99** [comment]
> Is it possible that your Go version is outdated?

Hi @wxiaoyun, It somehow resolved by itself after updating my go version to 1.22.4? Might've also been my GOPATH in my `.zshrc` file, but I'm not entirely sure. Either way, it works for me now. Thanks!
