### ISSUE TITLE
Username already taken even though there are no records in database

### ISSUE THREAD

**Issue by tankh99** [DYOC-Chatbot/chatbot-backend#7]
This issue occurs when trying to sign up as a new user with an empty database. 

<img width="1440" alt="Screenshot 2024-05-24 at 5 50 12 AM" src="https://github.com/DYOC-Chatbot/chatbot-backend/assets/56617918/016e95b7-5546-44cd-ab2e-bc65eea46a66">

**Comment by wxiaoyun** [comment]
Thats strange. When I use postman, I dont have this problem

Can you show a screenshot of the your db table rows with dbeaver or pgadmin and the logs from the backend

**Comment by seelengxd** [comment]
do send screenshots of the nextjs app on terminal as well (ps i am still overseas w/o my laptop, havent looked at the prs)

currently if the frontend sign up has **any**
error ull get that

**Comment by tankh99** [comment]
Here are the logs from the frontend

```
⨯ TypeError: fetch failed
    at async signUp (./src/api/auth.ts:41:22)
digest: "4241877147"
Cause: AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1117:18)
    at afterConnectMultiple (node:net:1684:7)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED ::1:8000
        at createConnectionError (node:net:1647:14)
        at afterConnectMultiple (node:net:1677:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 8000
    },
    Error: connect ECONNREFUSED 127.0.0.1:8000
        at createConnectionError (node:net:1647:14)
        at afterConnectMultiple (node:net:1677:16)
        at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 8000
    }
  ]
}
 POST /signup 500 in 20ms
```

As well as my rows in the database.

<img width="922" alt="Screenshot 2024-05-25 at 6 10 05 AM" src="https://github.com/DYOC-Chatbot/chatbot-backend/assets/56617918/c8017296-1c19-44bc-a955-2bf800214d44">

@ForAeons  the admin record was created in the database only when I made a signup  API call directly to the backend, but when signing up again with a new user like admin123 on the frontend, it gives the same error as before

<img width="1436" alt="Screenshot 2024-05-25 at 6 10 42 AM" src="https://github.com/DYOC-Chatbot/chatbot-backend/assets/56617918/d95990b0-2eb3-4120-b9d1-de6c2fd983cb">

**Comment by tankh99** [comment]
Actually, this was an .env issue. I blindly followed the setup instructions for .env with the value 

`NEXT_PUBLIC_BACKEND_URL=http://localhost:8000/api`

But the port was wrong, resulting in a faulty API call. Nothing wrong with backend or FE after making this fix. Will be closing this
